# Generated by Django 5.1.6 on 2025-03-27 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('shopkeeper', 'Shopkeeper'), ('staff', 'Staff'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='ShopkeeperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150, unique=True)),
                ('service_type', models.CharField(max_length=100)),
                ('specializations', models.JSONField()),
                ('experience', models.PositiveIntegerField()),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('certification_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='aadhar_docs/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('payment_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI Payment')], max_length=10)),
                ('individual_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
